# Generated by Django 2.1.7 on 2021-04-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LearningManagementSytem', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('course_img', models.ImageField(blank=True, upload_to='course_image')),
                ('level', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('dated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Accept'), ('R', 'Reject')], max_length=8)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningManagementSytem.UserProfile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningManagementSytem.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningManagementSytem.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('dated', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='course_lecture_videos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.Courses')),
            ],
        ),
    ]
