# Generated by Django 3.2 on 2021-05-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructor.courses'),
        ),
    ]
